/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package interfacegrafica;
import classededados.Aluno;
import persistencia.AlunoPersistencia;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;


/**
 *
 * @author Giu
 */
public class JanelaApresentacao extends javax.swing.JFrame {

    /**
     * Creates new form JanelaApresentacao
     */
    public JanelaApresentacao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonListarOsAlunos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDados = new javax.swing.JTable();
        jButtonListarOsAlunosArrayList = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonListarOsAlunos.setText("Listar os Alunos - vetor");
        jButtonListarOsAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarOsAlunosActionPerformed(evt);
            }
        });

        jTableDados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Matricula", "Nome"
            }
        ));
        jScrollPane1.setViewportView(jTableDados);

        jButtonListarOsAlunosArrayList.setText("Listar os Alunos - ArrayList");
        jButtonListarOsAlunosArrayList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarOsAlunosArrayListActionPerformed(evt);
            }
        });

        jButtonLimpar.setText("Limpar");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jButtonListarOsAlunos)
                .addGap(91, 91, 91)
                .addComponent(jButtonLimpar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addComponent(jButtonListarOsAlunosArrayList)
                .addGap(71, 71, 71))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonListarOsAlunos)
                    .addComponent(jButtonListarOsAlunosArrayList)
                    .addComponent(jButtonLimpar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonListarOsAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarOsAlunosActionPerformed
        // TODO add your handling code here:
        try{
            ///Users/eugeniojulio/Documents/PadroesDeProjetos/Iterator/ExemploEmJava/Iterator/ProjetoSemIterator/src/dados/ArquivoAlunos_28_33_120_csv.csv
            AlunoPersistencia dados = new AlunoPersistencia("./src/dados/ArquivoAlunos_28_33_120_csv.csv");
            Aluno[] valores = dados.listagemDeAlunosVetor();
           
            DefaultTableModel model =  (DefaultTableModel) jTableDados.getModel();
            model.setNumRows(0);
            
            for(int pos=0; pos < valores.length; pos++){
                String[] linha = new String[2];
                linha[0]= valores[pos].getMatricula();
                linha[1]= valores[pos].getNome();
                model.addRow(linha);
            }
            
        }catch(Exception erro){
            JOptionPane.showMessageDialog(rootPane, erro);
        }
    }//GEN-LAST:event_jButtonListarOsAlunosActionPerformed

    private void jButtonListarOsAlunosArrayListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarOsAlunosArrayListActionPerformed
        // TODO add your handling code here:
        try{
                                                           ///Users/eugeniojulio/Documents/PadroesDeProjetos/Iterator/ExemploEmJava/Iterator/ProjetoSemIterator/src/dados/ArquivoAlunos_28_33_120_csv.csv
            AlunoPersistencia dados = new AlunoPersistencia("./src/dados/ArquivoAlunos_28_33_120_csv.csv");
            ArrayList<Aluno> valores = dados.listagemDeAlunosArrayList();
           
            DefaultTableModel model =  (DefaultTableModel) jTableDados.getModel();
            model.setNumRows(0);
            
            for(int pos=0; pos < valores.size(); pos++){
                String[] linha = new String[2];
                linha[0]= valores.get(pos).getMatricula();
                linha[1]= valores.get(pos).getNome();
                model.addRow(linha);
            }
            
        }catch(Exception erro){
            JOptionPane.showMessageDialog(rootPane, erro);
        }
        
    }//GEN-LAST:event_jButtonListarOsAlunosArrayListActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model =  (DefaultTableModel) jTableDados.getModel();
        model.setNumRows(0);
    }//GEN-LAST:event_jButtonLimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaApresentacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaApresentacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaApresentacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaApresentacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaApresentacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonListarOsAlunos;
    private javax.swing.JButton jButtonListarOsAlunosArrayList;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDados;
    // End of variables declaration//GEN-END:variables
}
